"""RBF kernel-ridge column — the contract.

The claim this code exists to support is "the nonlinear readout beats the linear one." That claim
is only worth anything if the LINEAR column is provably the untouched published path, so the
load-bearing tests here are not about the RBF numbers at all -- they pin that turning --rbf on
cannot move the control, and that sharing the GEMMs cannot move either fit.

The second thing worth testing is that the nonlinearity is actually LIVE: a kernel ridge that has
silently collapsed to a linear fit would still print plausible AUROCs. So one test builds a task no
linear probe can do at all and requires the RBF column to solve it.
"""
from __future__ import annotations

import numpy as np
import pytest

from scripts.neuroprobe import v3_board_readout as R
from scripts.neuroprobe.v3_board_readout import (
    GAMMA_MULTS,
    LAM_MULTS,
    _lam_grid,
    _lam_grid_rbf,
    _linear_grams,
    _pc_project,
    _select_lam,
)

# d > n throughout, because that is the ONLY regime the caller ever shares grams in: _lam_grid
# takes the primal when d < n, and the primal is a different (equally valid) arithmetic path whose
# AUROCs differ in the 5th decimal. Testing the share in the primal regime would fail for a reason
# that can never occur in a board run.
_N, _D = 60, 200


def _split(n=_N, d=_D, *, kind="linear", seed=0):
    """(z_tr, y_tr, evals) on a task of the requested geometry, standardized like the board."""
    rng = np.random.default_rng(seed)
    x = rng.normal(size=(3 * n, d)).astype(np.float32)
    if kind == "linear":
        y = (x[:, 0] > 0).astype(np.float64)
    elif kind == "xor":
        # THE NONLINEARITY PROBE. y is the parity of two signs, so every linear functional of x is
        # exactly uninformative: E[y | x_j] is flat in x_j for all j. A linear ridge cannot beat
        # chance here no matter how λ is set; an RBF kernel can.
        y = ((x[:, 0] > 0) ^ (x[:, 1] > 0)).astype(np.float64)
    elif kind == "xor_lowrank":
        # XOR carried by a LOW-RANK, HIGH-VARIANCE subspace inside a wide ambient space -- the
        # honest caricature of the board's features, where 1.6e6 coordinates are generated by a
        # few hundred electrodes' worth of correlated activity and the separability work measured
        # that the top 32 directions carry the content. PCA can only denoise when signal and
        # variance coincide; under the iid fixture above they do not, and PCA is powerless BY
        # CONSTRUCTION. Testing the PC columns on iid noise would test the wrong claim.
        r = 8
        u = rng.normal(size=(3 * n, r))
        w = rng.normal(size=(r, d)) / np.sqrt(r)
        x = (u @ w * 4.0 + rng.normal(size=(3 * n, d))).astype(np.float32)
        y = ((u[:, 0] > 0) ^ (u[:, 1] > 0)).astype(np.float64)
    elif kind == "constant":
        x = np.zeros_like(x)
        y = (rng.random(3 * n) > 0.5).astype(np.float64)
    else:
        raise ValueError(kind)
    mu, sd = x[:n].mean(0), x[:n].std(0) + 1e-8
    z = ((x - mu) / sd).astype(np.float32)
    return z[:n], y[:n], {"val": (z[n:2 * n], y[n:2 * n]), "test": (z[2 * n:], y[2 * n:])}


def _best_test(grid):
    return _select_lam(grid)["test"]


# --------------------------------------------------------------------------------------------
# THE CONTROL MUST NOT MOVE
# --------------------------------------------------------------------------------------------

def test_sharing_grams_is_BIT_IDENTICAL_to_computing_them_inline():
    """The whole design rests on this. If precomputing the GEMMs to feed the RBF column perturbs
    the linear column by even a ULP, then --rbf silently re-runs the published number and the
    'control' is a different fit that merely looks the same."""
    z, y, ev = _split()
    solo = _lam_grid(z, y, ev)
    shared = _lam_grid(z, y, ev, grams=_linear_grams(z, ev))
    for name in ("val", "test"):
        for m in LAM_MULTS:
            assert solo[name][m] == shared[name][m], f"{name} λ={m} moved"


def test_rbf_flag_off_leaves_no_extra_column_and_rbf_on_leaves_the_linear_one_intact():
    """--rbf is ADDITIVE. It appends a column; it must not edit one."""
    z, y, ev = _split()
    base = _lam_grid(z, y, ev)
    gr = _linear_grams(z, ev)
    _ = _lam_grid_rbf(z, y, ev, grams=gr)          # fitting RBF off the shared grams...
    after = _lam_grid(z, y, ev, grams=gr)          # ...must not have consumed or mutated them
    for name in ("val", "test"):
        for m in LAM_MULTS:
            assert base[name][m] == after[name][m]


def test_rbf_does_not_mutate_the_feature_matrices():
    z, y, ev = _split()
    before = [z.copy()] + [v[0].copy() for v in ev.values()]
    _lam_grid_rbf(z, y, ev)
    after = [z] + [v[0] for v in ev.values()]
    for b, a in zip(before, after):
        assert np.array_equal(b, a)


# --------------------------------------------------------------------------------------------
# THE NONLINEARITY MUST BE LIVE
# --------------------------------------------------------------------------------------------

def test_rbf_solves_a_task_the_linear_ridge_CANNOT():
    """XOR in LOW dimension: chance for any linear probe, by construction. A kernel ridge that had
    collapsed to a linear fit would fail this and nothing else in the suite would notice."""
    z, y, ev = _split(d=4, kind="xor", seed=3)
    lin, rbf = _best_test(_lam_grid(z, y, ev)), _best_test(_lam_grid_rbf(z, y, ev))
    assert lin < 0.65, f"the linear control should be near chance on XOR, got {lin}"
    assert rbf > 0.85, f"RBF failed a task it must solve, got {rbf}"


def test_the_SAME_xor_becomes_unsolvable_once_uninformative_dimensions_are_added():
    """🔴 THE COLUMN'S FAILURE MODE, PINNED. The signal is untouched -- the same two coordinates
    still determine y -- but padding with noise directions makes every pairwise distance nearly
    equal, the kernel flattens toward constant, and NO γ in the grid recovers it. So a null RBF
    result on the real board is ambiguous by default: it may mean 'no nonlinearity to find' or
    merely 'd too large'. That is exactly why the fit records sd(d²)/mean(d²), and why the PC
    columns exist."""
    z, y, ev = _split(d=400, kind="xor", seed=3)
    assert _best_test(_lam_grid_rbf(z, y, ev)) < 0.65


def test_rbf_solves_a_WIDE_task_when_the_width_is_LOW_RANK():
    """⭐ THE PRECONDITION THE REAL BOARD TURNS ON. d=400 >> n, so raw dimension alone does NOT
    doom the kernel -- what matters is EFFECTIVE dimension. Here the width is generated by 8
    latent factors, distances stay informative, and RBF solves an XOR the linear ridge cannot
    (measured .87 vs .48). enc12_elec is 1.6e6 wide but generated by a few hundred electrodes, so
    which of this and the iid case it resembles is an empirical question about the features --
    answered by the sd(d²)/mean(d²) the fit records, not by the width."""
    z, y, ev = _split(n=180, d=400, kind="xor_lowrank", seed=3)
    lin = _best_test(_lam_grid(z, y, ev))
    rbf = _best_test(_lam_grid_rbf(z, y, ev))
    assert lin < 0.65, f"linear must be near chance on XOR, got {lin}"
    assert rbf > 0.80, f"RBF should solve a low-rank XOR, got {rbf}"


def test_pc_projection_PRESERVES_performance_where_raw_rbf_already_works():
    """🚫 THE PC COLUMNS ARE NOT A RESCUE — measured, not assumed. Where the data is genuinely
    low-rank, raw RBF is ALREADY fine and projecting buys nothing (raw .873 vs pc8 .883, inside
    noise). They are cheap extra columns testing a different question -- whether TRIMMING helps --
    and this test pins only that trimming does not DESTROY a working fit."""
    z, y, ev = _split(n=180, d=400, kind="xor_lowrank", seed=3)
    raw = _best_test(_lam_grid_rbf(z, y, ev))
    for k in (16, 32):
        assert _best_test(_lam_grid_rbf(z, y, ev, n_pc=k)) > raw - 0.08


def test_pc_projection_does_NOTHING_when_variance_carries_no_signal():
    """The honest limit, pinned so the column is never oversold: with iid features the leading PCs
    are arbitrary directions, and projecting onto them cannot find a signal that is not aligned
    with variance. ⇒ PCA is NOT a general cure for concentration."""
    z, y, ev = _split(n=180, d=400, kind="xor", seed=3)
    raw = _best_test(_lam_grid_rbf(z, y, ev))
    pc = max(_best_test(_lam_grid_rbf(z, y, ev, n_pc=k)) for k in (16, 32))
    assert abs(pc - raw) < 0.15 and pc < 0.70


def test_pc_projection_is_anchor_side_only():
    """V is the train Gram's eigenbasis. If an eval row could inform it, the column would be
    selecting its own representation on the data it is scored on."""
    z, y, ev = _split()
    g, kern = _linear_grams(z, ev)
    p_tr, p_e = _pc_project(g, kern, 32)
    assert p_tr is not None and p_e is not None
    zv, yv = ev["val"]
    ev2 = dict(ev, val=(zv * 3.0, yv))                 # perturb an eval block...
    g2, kern2 = _linear_grams(z, ev2)
    p_tr2, _ = _pc_project(g2, kern2, 32)
    assert p_tr2 is not None
    assert np.allclose(p_tr, p_tr2)                    # ...the TRAIN basis must not move


def test_rbf_is_competitive_on_a_task_the_linear_ridge_DOES_solve():
    """The other side of the ledger: the extra capacity must not wreck an easy linear task, or the
    column could never be reported as a single readout."""
    z, y, ev = _split(kind="linear", seed=5)
    lin, rbf = _best_test(_lam_grid(z, y, ev)), _best_test(_lam_grid_rbf(z, y, ev))
    assert rbf > lin - 0.05, f"RBF {rbf} collapsed against linear {lin}"


# --------------------------------------------------------------------------------------------
# THE GRID AND ITS INVARIANTS
# --------------------------------------------------------------------------------------------

def test_trace_invariant_holds_so_lambda_means_the_same_thing_at_every_gamma():
    """diag(K)==1 ⇒ trace(K)/n==1. Asserted inside the fit; this pins that the assert is reachable
    and true on real inputs, so the γ and λ axes stay separable."""
    z, _y, ev = _split()
    g, _k = _linear_grams(z, ev)
    sq = np.diag(g).copy()
    d2 = np.maximum(sq[:, None] + sq[None, :] - 2.0 * g, 0.0)
    med = float(np.median(d2[np.triu_indices(len(sq), k=1)]))
    for gm in GAMMA_MULTS:
        k = np.exp(-(gm / med) * d2)
        assert np.allclose(np.diag(k), 1.0)
        assert abs(float(np.trace(k)) / len(sq) - 1.0) < 1e-9


def test_returned_grid_has_the_SAME_SHAPE_as_the_linear_one():
    """_select_lam, the tie census and the lam_pin diagnostics are shared code. If the RBF fit
    returned a differently-keyed grid they would silently read the wrong thing."""
    z, y, ev = _split()
    lin, rbf = _lam_grid(z, y, ev), _lam_grid_rbf(z, y, ev)
    assert set(rbf) == set(lin)
    for name in ("val", "test"):
        assert sorted(rbf[name]) == sorted(lin[name]) == sorted(LAM_MULTS)


def test_gamma_selection_is_recorded_for_the_end_of_grid_census():
    before = R._RBF_STATS["fits"]
    z, y, ev = _split()
    _lam_grid_rbf(z, y, ev)
    assert R._RBF_STATS["fits"] == before + 1
    assert sum(R._RBF_STATS["picked"].values()) == R._RBF_STATS["fits"]
    assert set(R._RBF_STATS["picked"]) <= set(GAMMA_MULTS)


def test_gamma_is_selected_on_VAL_never_on_TEST():
    """The one way this harness could cheat. Corrupting the test half must not change which γ wins,
    and therefore must not change the val curve that selection reads."""
    z, y, ev = _split(seed=11)
    clean = _lam_grid_rbf(z, y, ev)
    zt, yt = ev["test"]
    poisoned = dict(ev, test=(zt, 1.0 - yt))       # flip every test label
    dirty = _lam_grid_rbf(z, y, poisoned)
    for m in LAM_MULTS:
        assert clean["val"][m] == dirty["val"][m], "test labels leaked into the val curve"


def test_degenerate_train_half_returns_nan_not_a_crash_or_a_number():
    """All rows identical ⇒ no length scale exists. Inventing one would print a scored cell for a
    fit that never happened."""
    z, y, ev = _split(kind="constant")
    out = _lam_grid_rbf(z, y, ev)
    assert all(np.isnan(out["test"][m]) for m in LAM_MULTS)


def test_single_row_train_half_is_nan():
    z, y, ev = _split()
    out = _lam_grid_rbf(z[:1], y[:1], ev)
    assert all(np.isnan(out["test"][m]) for m in LAM_MULTS)


@pytest.mark.parametrize("kind", ["linear", "xor"])
def test_no_nan_leaks_into_a_healthy_fit(kind):
    z, y, ev = _split(kind=kind, seed=7)
    out = _lam_grid_rbf(z, y, ev)
    assert all(np.isfinite(out["test"][m]) for m in LAM_MULTS)
