#!/usr/bin/env python3
"""Render an sbatch wrapper from a spec, rsync repo to DCC, submit. One line out.

Usage (single-cell experiment):

    scripts/ablation/submit.py --name q1e_d64 \\
        --mode per-phoneme --patient S14 \\
        --folds 0-4 --seeds 0-2 \\
        --flag d_model=64 --flag backbone_depth=5 \\
        --walltime 8:00:00 --mem 32G

Output (one line):

    job_id=12345  sbatch=scripts/v14_core/_gen/q1e_d64_dcc.sh  jobs=15  out=/work/ht203/results/v14_per_phoneme/_gen/q1e_d64

The wrapper is written under scripts/v14_core/_gen/ (committable as audit trail
or gitignored — your call). The submission record is appended to
.ablation_submissions.jsonl so status.py / collect.py can recover the spec.

Pooled mode: pass --patients S14,S26,S33,S62 instead of --patient.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time

from _common import (
    LOCAL_REPO,
    REMOTE_LOGS,
    REMOTE_PY,
    REMOTE_REPO,
    REMOTE_RESULTS,
    log_submission,
    parse_flag_pairs,
    parse_folds,
    render_flag_args,
    rsync_repo,
    ssh,
)


SBATCH_TEMPLATE = """#!/bin/bash
# Auto-generated by scripts/ablation/submit.py — do not hand-edit.
# Spec: {spec_json}
#
# task_id = fold * n_seeds + seed_idx
#
#SBATCH --job-name={name}
#SBATCH --partition=coganlab-gpu
#SBATCH --array=0-{last_task}
#SBATCH --gpus=1
#SBATCH --cpus-per-task={cpus}
#SBATCH --mem={mem}
#SBATCH --time={walltime}
#SBATCH --output={remote_logs}/%x_%A_%a.out
#SBATCH --error={remote_logs}/%x_%A_%a.err

set -euo pipefail

FOLDS=({fold_list})
SEEDS=({seed_list})

task_id=${{SLURM_ARRAY_TASK_ID}}
seed_idx=$(( task_id % {n_seeds} ))
fold_idx=$(( task_id / {n_seeds} ))
fold=${{FOLDS[$fold_idx]}}
seed=${{SEEDS[$seed_idx]}}

REPO={remote_repo}
PYTHON={remote_py}
OUT_DIR={out_dir}

export LD_LIBRARY_PATH=/work/ht203/miniconda3/envs/speech/lib:${{LD_LIBRARY_PATH:-}}
export PYTHONPATH=${{REPO}}/src:${{PYTHONPATH:-}}

mkdir -p "${{OUT_DIR}}"
mkdir -p {remote_logs}

echo "[$(date -Is)] task=${{task_id}} fold=${{fold}} seed=${{seed}} name={name}"
nvidia-smi || true

cd "${{REPO}}"
${{PYTHON}} scripts/v14_core/train_v14_core.py \\
    --mode {mode} \\
    {patient_arg} \\
    --fold "${{fold}}" \\
    --seed "${{seed}}" \\
    {flag_args} \\
    --out-dir "${{OUT_DIR}}"
"""


NAME_RE = re.compile(r"^[a-zA-Z0-9_-]+$")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--name", required=True, help="Short tag, used in job-name + out-dir.")
    p.add_argument(
        "--mode",
        choices=("per-phoneme", "pooled", "slot"),
        default="per-phoneme",
    )
    p.add_argument("--patient", default=None, help="Single patient (per-phoneme/slot).")
    p.add_argument("--patients", default=None, help="Comma-list (pooled).")
    p.add_argument("--folds", default="0-4", help="e.g. '0-4' or '0,2,4'.")
    p.add_argument("--seeds", default="0-2", help="e.g. '0-2' or '0,1'.")
    p.add_argument(
        "--flag",
        action="append",
        default=[],
        help="Repeatable. k=v passed through to train_v14_core.py "
        "(use empty value for store_true, e.g. --flag no-parcel-embedding=).",
    )
    p.add_argument("--walltime", default="08:00:00")
    p.add_argument("--mem", default="32G")
    p.add_argument("--cpus", type=int, default=4)
    p.add_argument(
        "--out-dir",
        default=None,
        help=f"Remote out-dir. Default: {REMOTE_RESULTS}/v14_per_phoneme/_gen/<name>.",
    )
    p.add_argument(
        "--no-rsync",
        action="store_true",
        help="Skip the repo rsync — assume DCC is already in sync.",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Render the sbatch and print it. Do not rsync, do not sbatch.",
    )
    args = p.parse_args()

    if not NAME_RE.match(args.name):
        sys.exit(f"--name must match {NAME_RE.pattern!r}")

    if args.mode == "pooled":
        if not args.patients:
            sys.exit("--patients is required for pooled mode")
        patient_arg = f'--patients "{args.patients}"'
    else:
        if not args.patient:
            sys.exit("--patient is required for per-phoneme/slot mode")
        patient_arg = f'--patient "{args.patient}"'

    folds = parse_folds(args.folds)
    seeds = parse_folds(args.seeds)
    n_jobs = len(folds) * len(seeds)
    flags = parse_flag_pairs(args.flag)
    flag_args = render_flag_args(flags)

    out_dir = args.out_dir or f"{REMOTE_RESULTS}/v14_per_phoneme/_gen/{args.name}"

    spec = {
        "name": args.name,
        "mode": args.mode,
        "patient": args.patient,
        "patients": args.patients,
        "folds": folds,
        "seeds": seeds,
        "flags": flags,
        "out_dir": out_dir,
        "walltime": args.walltime,
        "mem": args.mem,
    }

    sbatch_text = SBATCH_TEMPLATE.format(
        name=args.name,
        spec_json=json.dumps(spec, sort_keys=True),
        last_task=n_jobs - 1,
        cpus=args.cpus,
        mem=args.mem,
        walltime=args.walltime,
        remote_logs=REMOTE_LOGS,
        fold_list=" ".join(str(f) for f in folds),
        seed_list=" ".join(str(s) for s in seeds),
        n_seeds=len(seeds),
        remote_repo=REMOTE_REPO,
        remote_py=REMOTE_PY,
        out_dir=out_dir,
        mode=args.mode,
        patient_arg=patient_arg,
        flag_args=flag_args,
    )

    sbatch_dir = LOCAL_REPO / "scripts" / "v14_core" / "_gen"
    sbatch_dir.mkdir(parents=True, exist_ok=True)
    sbatch_path = sbatch_dir / f"{args.name}_dcc.sh"
    sbatch_path.write_text(sbatch_text)
    sbatch_path.chmod(0o755)

    if args.dry_run:
        print(sbatch_text)
        print(f"# wrote {sbatch_path}")
        return 0

    if not args.no_rsync:
        rsync_repo()

    remote_sbatch = f"{REMOTE_REPO}/scripts/v14_core/_gen/{args.name}_dcc.sh"
    out = ssh(f"sbatch --parsable {remote_sbatch}").strip()
    job_id = out.splitlines()[-1].strip() if out else ""
    if not job_id.isdigit():
        sys.exit(f"could not parse job id from sbatch output: {out!r}")

    rec = {
        "ts": int(time.time()),
        "job_id": job_id,
        "name": args.name,
        "n_jobs": n_jobs,
        "out_dir": out_dir,
        "sbatch": str(sbatch_path.relative_to(LOCAL_REPO)),
        "spec": spec,
    }
    log_submission(rec)

    print(
        f"job_id={job_id}  sbatch={sbatch_path.relative_to(LOCAL_REPO)}  "
        f"jobs={n_jobs}  out={out_dir}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
